#ifndef _GRUVBOX_DARK_HARD
#define _GRUVBOX_DARK_HARD

#define GRUVBOX_DARK_HARD_BLUE    LV_COLOR_MAKE(69,113,136)
#define GRUVBOX_DARK_HARD_ORANGE  LV_COLOR_MAKE(254,128,25)
#define GRUVBOX_DARK_HARD_RED     LV_COLOR_MAKE(251,73,52)
#define GRUVBOX_DARK_HARD_TEAL    LV_COLOR_MAKE(29,32,33)
#define GRUVBOX_DARK_HARD_WHITE   LV_COLOR_MAKE(251,241,199)

#define BACKGROUND_COLOR    GRUVBOX_DARK_HARD_TEAL
#define BLUE_BUTTON_COLOR   GRUVBOX_DARK_HARD_BLUE
#define LINE_COLOR          GRUVBOX_DARK_HARD_WHITE
#define RED_BUTTON_COLOR    GRUVBOX_DARK_HARD_RED
#define SKILL_BUTTON_COLOR  GRUVBOX_DARK_HARD_ORANGE
#define TEXT_COLOR          GRUVBOX_DARK_HARD_WHITE

#endif /* ifndef _GRUVBOX_DARK_HARD */
