#ifndef _HORIZON_DARK_
#define _HORIZON_DARK_

#define HORIZON_DARK_BLACK  LV_COLOR_MAKE (28,30,38)
#define HORIZON_DARK_BLUE   LV_COLOR_MAKE (38,187,217)
#define HORIZON_DARK_RED    LV_COLOR_MAKE (233,60,88)
#define HORIZON_DARK_YELLOW LV_COLOR_MAKE (239,185,147)
#define HORIZON_DARK_WHITE  LV_COLOR_MAKE (203,206,208)

#define BACKGROUND_COLOR    HORIZON_DARK_BLACK
#define BLUE_BUTTON_COLOR   HORIZON_DARK_BLUE
#define LINE_COLOR          HORIZON_DARK_WHITE
#define RED_BUTTON_COLOR    HORIZON_DARK_RED
#define SKILL_BUTTON_COLOR  HORIZON_DARK_YELLOW
#define TEXT_COLOR          HORIZON_DARK_BLACK

#endif /* ifndef _HORIZON_DARK_ */
