#ifndef _OUTRUN_DARK_
#define _OUTRUN_DARK_

#define OUTRUN_DARK_BLACK   LV_COLOR_MAKE(0,0,42)
#define OUTRUN_DARK_BLUE    LV_COLOR_MAKE(102,176,225)
#define OUTRUN_DARK_RED     LV_COLOR_MAKE(255,66,77)
#define OUTRUN_DARK_ORANGE  LV_COLOR_MAKE(255,140,0)
#define OUTRUN_DARK_WHITE   LV_COLOR_MAKE(208,240,240)

#define BACKGROUND_COLOR    OUTRUN_DARK_BLACK
#define BLUE_BUTTON_COLOR   OUTRUN_DARK_BLUE
#define LINE_COLOR          OUTRUN_DARK_WHITE
#define RED_BUTTON_COLOR    OUTRUN_DARK_RED
#define SKILL_BUTTON_COLOR  OUTRUN_DARK_ORANGE
#define TEXT_COLOR          OUTRUN_DARK_WHITE

#endif /* ifndef _OUTRUN_DARK_*/
